### ISSUE TITLE
CSS Inheritance

### ISSUE THREAD

**Issue by reviewer99** [Parbles/prj-rev-bwfs-dasmoto#5]
When writing your CSS styles it is best to try and eliminate any duplicate styles found in your stylesheet as it makes it easier to make changes in the future.

For example here instead of the following:
```CSS
#brushes {
  font-family: Helvetica;
  font-size: 32px;
  font-weight:bold;
  color: white;
  background-color: mediumspringgreen;
}

#frames {
  font-family: Helvetica;
  font-size: 32px;
  font-weight:bold;
  color: white;
  background-color: lightcoral;
}

#paint {
  font-family: Helvetica;
  font-size: 32px;
  font-weight:bold;
  color: white;
  background-color: skyblue;
}
```

You could have done something like this:
```CSS
h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight:bold;
  color: white;
}

#brushes {
  background-color: mediumspringgreen;
}

#frames {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}

```

This way all your `h2`s inherit the styles they all share and you only need to apply the unique background they all have.

https://github.com/Parbles/prj-rev-bwfs-dasmoto/blob/7680f3f39846da610a1b60dd163ad02d8df55926/Dasmoto/Resources/style.css#L19-L41
